POST {{client.host}}/Accounts/ChangePassword
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "oldPassword": "Pass123",
  "newPassword": "Pass1234@",
  "confirmPassword": "Pass1234@"
}


