GET {{client.host}}/trade?pageSize=5&pageNumber=1&search=&sorts[0].sortBy=Swap&sorts[0].sortOrder=asc&sorts[0].order=1&id={{tradingPlanId}}
Content-Type: application/json
Authorization: Bearer {{token}}